---
- name: Installing Jenkins server
  hosts: elliot01
  become: true
  gather_facts: false
  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest
      ignore_errors: yes

    - name: Installing some packages
      yum:
        name: 
          - wget
          - java
          - git
          - vim
        state: latest

    - name: Download foo.conf
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        mode: '0440'
      
    - name: Import a key from a url
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Update all packages to their latest version
      yum:
        update_cache: yes
      ignore_errors: true

    - name: Installing Jenkins
      yum:
        name: jenkins
        state: latest

    - name: Make sure a service unit is running
      systemd:
        name: jenkins
        state: started
...