---
- name: Installing Jenkins server
  hosts: all
  become: true
  remote_user: ubuntu
  gather_facts: false
  tasks:
    - name: Update all packages to their latest version
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
      ignore_errors: true

    - name: Installing some packages
      apt:
        name: 
          - wget
          - git
          - curl
          - openjdk-11-jre
          - vim
        state: latest
      ignore_errors: true

    - name: checking repository
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian/jenkins.io.key | sudo tee \
        /usr/share/keyrings/jenkins-keyring.asc > /dev/null
        echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
        https://pkg.jenkins.io/debian binary/ | sudo tee \
        /etc/apt/sources.list.d/jenkins.list > /dev/null

    - name: Update all packages to their latest version
      apt:
        update_cache: yes
      ignore_errors: true

    - name: Installing Jenkins
      apt:
        name: jenkins
        state: latest

    - name: Make sure a service unit is running
      systemd:
        name: jenkins
        state: started
...
